#!/bin/sh
set -eu

if [ -z "${NAVIDROME_ADMIN_PASSWORD:-}" ]; then
  echo "NAVIDROME_ADMIN_PASSWORD must be set to generate navidrome.toml" >&2
  exit 1
fi

cat > /data/navidrome.toml <<EOF2
# Auto-generated by docker compose helper. Edit with care.
DevAutoCreateAdminPassword = "${NAVIDROME_ADMIN_PASSWORD}"
EOF2

echo "Generated /data/navidrome.toml for Navidrome."
